### ISSUE TITLE
求助，"error":"phprs\\util\\exceptions\\NotFound","message

### ISSUE THREAD

**Issue by admimistrator** [caoym/phpboot#18]
`<?php
header("Content-Type:text/html;charset=utf-8");
use phprs\ezsql\Sql;

/**
 * 
 * @author caoym
 * @path("/wwwwwww")
 */
class HelloWorld2
{
    /** 
     * @route({"GET","/"})
	 * @param({"arg0","$._GET.arg0"})
     */
    public function doSomething1() {
		try{
			$pdo = $this->db;
			$str = Sql::update('report')->set( 'lv = 1' )->where('id=?',$arg0)->exec($pdo);
			$pdo->commit();
		}
		catch (Exception $e) {
           
            $pdo->rollBack();
            throw $e;
		}
		return "1";    
	}
    
    /**
     * @property({"default":"@db"}) 注入pdo实例
     */
    public $db;
}
`

这是我在phprs-restful-master\example\apis目录下新建的Helloworld2.php 文件 不知道为什么访问会报  3	0.0202	877496	header ( )	..\Bootstrap.php:42
{"error":"phprs\\util\\exceptions\\NotFound","message":""}
我把 HelloWorld.php 内容改成了
`<?php
header("Content-Type:text/html;charset=utf-8");
use phprs\ezsql\Sql;

/**
 * 
 * @author caoym
 * @path("/g")
 */
class HelloWorld
{
    /** 
     * @route({"GET","/"})
     */
    public function doSomething1() {
		$str = Sql::select('*')->from('report')->where( 'lv = 0' )->limit(1,1)->get($this->db);
		$str1= json_encode($str, JSON_UNESCAPED_UNICODE);  
		return $str1;    
	}
    
    /**
     * @property({"default":"@db"}) 注入pdo实例
     */
    public $db;
}`

这样访问又没有问题。真是奇怪，
配置文件 phprs-restful-master\example\conf.php内容
`<?php
return [
    "phprs\\Router"=>[
        "properties"=>[
            "export_apis"=>true,
            "url_begin"=>1, 
            "api_path"=>__DIR__.'/apis/',

        ]
    ],
    "phprs\\Invoker"=>[
        "properties"=>[
            
        ] 
    ],
    "db"=>[
		"singleton"=>true,
    	"class"=>"PDO",
    	"pass_by_construct"=>true,
    	"properties"=>[
    		"dsn"=>"mysql:host=127.0.0.1;dbname=report;charset=UTF8",
    		"username"=>"root",
    		"passwd"=>"xxx"  		
    	]
    ]
    
];	
`

**Comment by caoym** [comment]
@param({"arg0","$._GET.arg0"})
public function doSomething1() {}
以上, $._GET.arg0没有在doSomething1方法中有对应参数,所以解析出错了, 路由没有加载成功,  看一下PHP的error_log, 应该有提示
