### ISSUE TITLE
How about add 401 unAuth error response

### ISSUE THREAD

**Issue by januslo** [caoym/phpboot#19]
I need to info user to input the credentials via Basic auth. current phprs-restful version support 403 only. may I ask for 401 response? or I can help to do the implementation as long as the author agree for that.

**Comment by caoym** [comment]
Use phprs\util\exceptions\ExceptionWithHttpStatus, for example:
```PHP
$err = new ExceptionWithHttpStatus();
$err->status = '401 Unauthorized';
throw $err;
```
or:
```PHP
class Unauthorized extends ExceptionWithHttpStatus
{
    public function __construct($message = '', $code = 0, \Exception $previous = null){
        parent::__construct($message, $code, $previous);
        $this->status = '401 Unauthorized';
    }
}

throw new Unauthorized('.....');
```

**Comment by januslo** [comment]
Wooo, that cool. Thx and plz close this issue

发自我的 iPhone
