### ISSUE TITLE
想问一下如何添加根据路径的hook

### ISSUE THREAD

**Issue by kilingzhang** [caoym/phpboot#23]
想问一下如何添加根据路径的hook,我按照文档中添加的方法不太对.文档提供的方法参数都是不对应的.希望解答下!

**Comment by caoym** [comment]
1. 可以看一下示例 http://phpboot.org/zh/latest/advanced/hook.html

**Comment by caoym** [comment]
1. 可以看一下说明 http://phpboot.org/zh/latest/advanced/hook.html
2. 示例代码 https://github.com/caoym/phpboot-example 中，Cors就是用 Hook 实现的，可以参考
3. 如果还是有问题，可以加 QQ 群讨论 185193529
