### ISSUE TITLE
Class App\Controllers\Books does not exist

### ISSUE THREAD

**Issue by nirvana72** [caoym/phpboot#27]
win10 nginx php7.3
composer 安装好依赖，git 拉取example 项目
目录结构，拉取后就没动用
App
-Controllers
--Books.php
config
public
vendor
composer.json
-----------------------------------------------------------------------------
运行项目报错
Fatal error: Uncaught ReflectionException: Class App\Controllers\Books does not exist in E:\php\phpboot\vendor\caoym\phpboot\src\Annotation\ContainerBuilder.php:42 Stack trace: #0 E:\php\phpboot\vendor\caoym\phpboot\src\Annotation\ContainerBuilder.php(42): ReflectionClass->__construct('App\\Controllers...') #1 E:\php\phpboot\vendor\caoym\phpboot\src\Controller\ControllerContainerBuilder.php(62): PhpBoot\Annotation\ContainerBuilder->build('App\\Controllers...') #2 E:\php\phpboot\vendor\caoym\phpboot\src\Application.php(153): PhpBoot\Controller\ControllerContainerBuilder->build('App\\Controllers...') #3 E:\php\phpboot\vendor\caoym\phpboot\src\Application.php(213): PhpBoot\Application->loadRoutesFromClass('App\\Controllers...', Array) #4 E:\php\phpboot\public\index.php(37): PhpBoot\Application->loadRoutesFromPath('E:/php/phpboot/...', 'App\\Controllers') #5 {main} thrown in E:\php\phpboot\vendor\caoym\phpboot\src\Annotation\ContainerBuilder.php on line 42

-------------------------------------------------------------------------

请教一下， 是我哪个地方遗漏了么

**Comment by wuyougan** [comment]
用例子没有问题，但自己写的也出现这个错误，你后来怎么解决的？
